spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: business-transaction
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.116:8848

dubbo:
  scan:
    base-packages: com.funtl.spring.cloud.alibaba.business.controller
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://192.168.0.116:8848

server:
  port: 12001

management:
  endpoints:
    web:
      exposure:
        include: "*"
